const productsData = [
    {
      name: "MacBook Pro 14",
      brand: "Apple",
      price: 2499,
      description: "Potente notebook con chip M2 Pro para tareas exigentes.",
      image: "https://example.com/images/macbook-pro-14.jpg",
      product: "notebook",
    },
    {
      name: "Galaxy S23 Ultra",
      brand: "Samsung",
      price: 1199,
      description: "Smartphone de alto rendimiento con cámara profesional de 200 MP.",
      image: "https://example.com/images/galaxy-s23-ultra.jpg",
      product: "smartphone",
    },
    {
      name: "Sony WH-1000XM5",
      brand: "Sony",
      price: 399,
      description: "Auriculares inalámbricos con cancelación de ruido líder en el mercado.",
      image: "https://example.com/images/sony-wh-1000xm5.jpg",
      product: "headphones",
    },
    {
      name: "LG OLED C2",
      brand: "LG",
      price: 1799,
      description: "Televisor OLED 4K con colores vibrantes y negros profundos.",
      image: "https://example.com/images/lg-oled-c2.jpg",
      product: "tv",
    },
    {
      name: "Dell XPS 13",
      brand: "Dell",
      price: 1399,
      description: "Notebook ultradelgada con pantalla InfinityEdge y gran rendimiento.",
      image: "https://example.com/images/dell-xps-13.jpg",
      product: "notebook",
    },
    {
      name: "iPhone 15 Pro",
      brand: "Apple",
      price: 1299,
      description: "El smartphone más avanzado de Apple con chip A17 Bionic.",
      image: "https://example.com/images/iphone-15-pro.jpg",
      product: "smartphone",
    },
    {
      name: "Bose QuietComfort 45",
      brand: "Bose",
      price: 329,
      description: "Auriculares con gran calidad de sonido y comodidad todo el día.",
      image: "https://example.com/images/bose-qc45.jpg",
      product: "headphones",
    },
    {
      name: "Samsung Neo QLED 8K",
      brand: "Samsung",
      price: 4999,
      description: "Televisor premium con resolución 8K y tecnología Quantum Mini LED.",
      image: "https://example.com/images/samsung-neo-qled-8k.jpg",
      product: "tv",
    },
    {
      name: "iPad Air 5",
      brand: "Apple",
      price: 599,
      description: "Tablet potente y ligera con chip M1 y pantalla Liquid Retina.",
      image: "https://example.com/images/ipad-air-5.jpg",
      product: "tablet",
    },
    {
      name: "Lenovo Yoga 9i",
      brand: "Lenovo",
      price: 1499,
      description: "Convertible 2 en 1 con pantalla táctil y excelente diseño.",
      image: "https://example.com/images/lenovo-yoga-9i.jpg",
      product: "notebook",
    },
    {
      name: "Google Pixel 8",
      brand: "Google",
      price: 899,
      description: "Smartphone con Android puro y excelente cámara fotográfica.",
      image: "https://example.com/images/google-pixel-8.jpg",
      product: "smartphone",
    },
    {
      name: "JBL Charge 5",
      brand: "JBL",
      price: 179,
      description: "Altavoz portátil con sonido potente y batería de larga duración.",
      image: "https://example.com/images/jbl-charge-5.jpg",
      product: "speaker",
    },
    {
      name: "Samsung Galaxy Tab S9",
      brand: "Samsung",
      price: 999,
      description: "Tablet premium con pantalla AMOLED y soporte para S Pen.",
      image: "https://example.com/images/galaxy-tab-s9.jpg",
      product: "tablet",
    },
    {
      name: "Razer Blade 15",
      brand: "Razer",
      price: 2499,
      description: "Laptop gamer con diseño elegante y alto rendimiento.",
      image: "https://example.com/images/razer-blade-15.jpg",
      product: "notebook",
    },
    {
      name: "Sony Bravia XR",
      brand: "Sony",
      price: 3499,
      description: "Televisor inteligente con tecnología Cognitive Processor XR.",
      image: "https://example.com/images/sony-bravia-xr.jpg",
      product: "tv",
    }
  ];
  
  export default productsData;
  